### ISSUE TITLE
Advantage over postcss-cli?

### ISSUE THREAD

**Issue by fregante** [otissv/postcss-build#1]
What is the advantage of using this over the official [postcss-cli](https://github.com/postcss/postcss-cli)?

**Comment by otissv** [comment]
postcss-build is a wrapper around postcss. The only thing added is to use a directory of files as the input.

**Comment by fregante** [comment]
That's [already in postcss-cli](https://github.com/code42day/postcss-cli#examples)

[<img width="501" alt="Use multiple plugins and multiple input files" src="https://cloud.githubusercontent.com/assets/1402241/15651750/49817472-2636-11e6-88e5-1faeaacbd82c.png">](https://github.com/code42day/postcss-cli#examples)

Either way, generally it's a good idea to extend an existing package, rather than publishing an alternative.

**Comment by bfred-it** [comment]
Generally it's a good idea to extend an existing package, rather than publishing an alternative one.

**Comment by otissv** [comment]
Will take another look at official

**Comment by otissv** [comment]
The advantage wasn't simply directory support, but nested directories.

The multiple input files doesn't seem to handle a nested directory structure. Please correct me if I'm wrong.

```
|-css
|    |-component
|    |    |-button
|    |       |-button.css
|    |
|    |-main.css   
|    
|-main.css
```

While you're correct I could have added nested directory support to post-cli, I wasn't really thinking of this along the lines of "publishing as an alternative". I had a module which I use so I put it on npm as it's easier for me to reuse between projects and computers and thought others might find it useful too.

The other minor advantage for me is I prefer this api.

I really just built this for me to use and put it on npm for me to use.

**Comment by fregante** [comment]
Fair enough :)
